train_dataset:
  root_dir: "data/recognition"
  train_split: True 
  transform: null
  linear_transform: True
  backbone: null
  gap_dim:  1

test_dataset:
  root_dir: "data/recognition"
  train_split: False
  transform: null
  linear_transform: True
  backbone: null
  gap_dim:  1

training_params:
  save_plots: True       ## null or True - save plots and results
  exp_name: "ann_try1"   ## string - name of the experiment , dir - plots/ann/<exp_name>
  run_experiments: True  ## False or True - run experiments for hyperparameter tuning
  hyperparameter_range:     ## only run if run_experiments is True
    learning_rate: [0.0003, 0.001]
    batch_size: [64, 256]
  default_param:        ## default parameters for training
    learning_rate: 0.001
    batch_size: 64
    num_epochs: 2
    model:
      num_feature: 150528
      num_class: 13
