train_dataset:
  root_dir: "data/recognition"
  train_split: True 
  transformation: True
  backbone: vit_large
  gap_dim: 7

test_dataset:
  root_dir: "data/recognition"
  train_split: False
  transformation: True
  backbone: vit_large
  gap_dim: 7

training_params:
  save_plots: True
  exp_name: "vit_large_pair_ann_fin"
  run_experiments: True
  hyperparameter_range:
    learning_rate: [0.001, 0.0003]
    batch_size: [32, 64, 256]
  default_param:
    learning_rate: 0.001
    batch_size: 64
    num_epochs: 30
    model:
      # layers: [1536, 512, 256, 1]  # 2*768=1536 input (concat pair), 1 output
      layers: [2048, 1024, 512, 1]  # 2*768=1536 input (concat pair), 1 output
